[SERVICE]
    Parsers_File /mnt/c/Users/tiya2/Downloads/fluent-bit-4.2.3-win64/fluent-bit-4.2.3-win64/parsers.conf

[INPUT]
    Name          tail
    Path          /mnt/c/Users/tiya2/Downloads/fluent-bit-4.2.3-win64/fluent-bit-4.2.3-win64/logs.txt
    Tag           mylogs
    Parser        custom_parser
    Read_from_Head true

[INPUT]
    Name          tail
    Path          /mnt/c/Users/tiya2/Downloads/fluent-bit-4.2.3-win64/fluent-bit-4.2.3-win64/json_logs.txt
    Tag           jsonlogs
    Parser        json_parser
    Read_from_Head true

[OUTPUT]
    Name         http
    Match        *
    Host         172.19.192.1
    Port         8080
    URI          /
    Format       json
    http_method  POST

