[SERVICE]
    Parsers_File C:\Users\tiya2\Downloads\fluent-bit-4.2.3-win64\fluent-bit-4.2.3-win64\parsers.conf
    Flush        1
    Log_Level    info

[INPUT]
    Name            tail
    Path            C:\Users\tiya2\Downloads\fluent-bit-4.2.3-win64\fluent-bit-4.2.3-win64\logs.txt
    Tag             mylogs
    Parser          custom_parser
    Read_from_Head  true

[INPUT]
    Name            tail
    Path            C:\Users\tiya2\Downloads\fluent-bit-4.2.3-win64\fluent-bit-4.2.3-win64\json_logs.txt
    Tag             jsonlogs
    Parser          json_parser
    Read_from_Head  true

[OUTPUT]
    Name         http
    Match        *
    Host         127.0.0.1
    Port         9000
    URI          /
    Format       json
    http_method  POST
