[PARSER]
    Name        custom_parser
    Format      regex
    Regex       ^(?<time>[^ ]+ [^ ]+) : (?<level>[^ ]+) : \[(?<file>[^ ]+) : (?<line>[0-9]+)\] : (?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S,%L
    Time_Keep   On

[PARSER]
    Name   json_parser
    Format json
